#!/bin/bash

## Backup the original .bashrc file
if ! test -f "${HOME}/.bashrc_orig"; then
	cp "${HOME}/.bashrc" "${HOME}/.bashrc_orig"
fi

## Update files 
cp "${HOME}/.bashrc_orig" "${HOME}/.bashrc"
cat >> "${HOME}/.bashrc" <<-EOF
	#
	# Tools setup for debian packaging
	DEBEMAIL=${EMAIL}
	DEBFULLNAME=${FULLNAME}
	export DEBEMAIL DEBFULLNAME
	git config --global user.email ${EMAIL}
	git config --global user.name ${FULLNAME}
EOF

if ! test -f "${HOME}/.devscripts"; then
	cat > "${HOME}/.devscripts" <<-EOF
		DEBUILD_DPKG_BUILDPACKAGE_OPTS="-i -I -us -uc"
		DEBUILD_LINTIAN_OPTS="-i -I --show-overrides"
		DEBSIGN_KEYID=${GPGKEYID}
EOF
fi

if ! test -f "${HOME}/.dput.cf"; then
	cat > "${HOME}/.dput.cf" <<-EOF
		[mentors]
		fqdn = mentors.debian.net
		incoming = /upload
		method = https
		allow_unsigned_uploads = 0
		progress_indicator = 2
		# Allow uploads for UNRELEASED packages
		allowed_distributions = .*
EOF
fi

if ! test -f "${HOME}/.gbp.conf"; then
	cat > "${HOME}/.gbp.conf" <<-EOF
		[DEFAULT]
		pristine-tar = True
		color = auto
EOF
fi

## Adapt uid and gid, if necessary
if test ${PGID:-1000} -ne $(id -g); then
	sudo groupmod --non-unique --gid ${PGID:-1000} maintainer
fi

if test ${PUID:-1000} -ne $(id -u); then
	sudo usermod --non-unique --uid ${PUID:-1000} maintainer
fi

## Adapt timezone
if test -f /usr/share/zoneinfo/${TZ}; then
	sudo ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
fi

## Update & upgrade if applicable
sudo apt update
sudo apt upgrade --yes 

## Call ssh-agent
eval "$(ssh-agent -s)"

## Run bash
/bin/bash
